deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0  # Please set it to the subnet address you obtained.
                  # If not set, by default all IP access is allowed.
  etcd:
    host:
      - ${{URL_ETCD:=}} #"http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

discovery:
  eureka:
    host:
    - ${{URL_EUREKA:=}} #"http://10.43.101.226:8761"
    prefix: /eureka/
    fetch_interval: 30
    weight: 100
    timeout:
    connect: 2000
    send: 2000
    read: 5000
